# Build and push the bitcoind docker image and deploy k8s resources.
# Will trigger when changes are made to the Dockerfile and k8s yamls in the main branch.
# Google Cloud Build documentation was referenced while compsing this file.

steps:
  - id: 'Docker build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/bitcoind/bitcoind:$COMMIT_SHA', '.']
  - id: 'Docker push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/bitcoind/bitcoind:$COMMIT_SHA']
  - id: 'k8s namespace'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=k8s/bitcoind-namespace.yaml
    - --location=us-central1
    - --cluster=bitcoind
    - --output=output-namespace
  - id: 'k8s deployment'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=k8s/bitcoind-deployment.yaml
    - --image=us-central1-docker.pkg.dev/$PROJECT_ID/bitcoind/bitcoind:$COMMIT_SHA
    - --location=us-central1
    - --cluster=bitcoind
    - --output=output-deployment
options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
