# Test building the docker image and run a terraform plan to review in PRs.
# Google Cloud Build documentation was referenced while compsing this file.

steps:
  - id: 'Docker build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.']
  - id: 'Terraform plan'
    name: 'hashicorp/terraform:1.9.5'
    script: |
      cd bitcoind/terraform
      terraform init
      terraform plan -var="gcp_project=$PROJECT_ID"
options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
