# Define a k8s deployment to run our bitcoind containers.
# Three replicas will run for redundancy.
# This could be improved by defining storage options and/or using a StatefulSet.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind
  namespace: bitcoind
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
      - name: bitcoind
        image: us-central1-docker.pkg.dev/bitcoind-example/bitcoind/bitcoind
        ports:
        - containerPort: 8333
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
      nodeSelector:
        cloud.google.com/gke-nodepool: bitcoind
