apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind
  namespace: bitcoind
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
        - name: bitcoind
          image: us-central1-docker.pkg.dev/bitcoind-example/bitcoind/bitcoind
          ports:
          - containerPort 8333
