apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
        - name: bitcoind
          ports:
          - containerPort 8333
